name: City Green OC
favicon: null
layout_spectrum: 0.19825
typography_spectrum: 0.87606
title: Artisan Tree Care -Organic Edible Gardens - Water Efficient Landscape Retrofits
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#38b813'
    - '#8b847c'
    - '#4ed113'
    - '#56ca22'
  brandStrength: 0.0625
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
