name: City Green OC
favicon: null
layout_spectrum: 0.7384903880301863
typography_spectrum: 0.917223131749779
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#38b813'
    - '#8b847c'
    - '#4ed113'
    - '#56ca22'
  brandStrength: 1
  lightness: 0.875
  saturation: 0.2413523697759956
  rhythmicContrast: 0.7472276876214892
purpose: []
